In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import random
from datetime import datetime, timedelta

In [2]:
engine = create_engine("mysql+pymysql://root:SEEni2003%40@localhost:1611/ar_risk_system")

In [3]:
# ----------------------------------------
# STEP 1: Basic Configuration
# ----------------------------------------

num_customers = 400

# Risk distribution
low_risk_count = int(num_customers * 0.40)
medium_risk_count = int(num_customers * 0.35)
high_risk_count = num_customers - (low_risk_count + medium_risk_count)

print("Low:", low_risk_count)
print("Medium:", medium_risk_count)
print("High:", high_risk_count)

Low: 160
Medium: 140
High: 100

In [4]:
# ----------------------------------------
# STEP 2: Create Risk Profile List
# ----------------------------------------

risk_profiles = (
    ["Low"] * low_risk_count +
    ["Medium"] * medium_risk_count +
    ["High"] * high_risk_count
)

# Shuffle to randomize distribution
random.shuffle(risk_profiles)

In [5]:
# ----------------------------------------
# STEP 3: Generate Customer Data
# ----------------------------------------

customer_ids = [f"CUST{i:04d}" for i in range(1, num_customers + 1)]

customer_types = ["Distributor", "Dealer", "Hospital"]
regions = ["North", "South", "East", "West"]

data = []

for i in range(num_customers):
    
    # Assign credit limit based on risk
    if risk_profiles[i] == "Low":
        credit_limit = random.randint(2000000, 5000000)  # Between 20 L to 50 L
    elif risk_profiles[i] == "Medium":
        credit_limit = random.randint(1000000, 3000000)  # Between 10 L to 30 L
    else:
        credit_limit = random.randint(500000, 2000000)   # Between 5 L to 20 L
    
    data.append([
        customer_ids[i],
        random.choice(customer_types),
        random.choice(regions),
        credit_limit,
        risk_profiles[i]
    ])

customers_df = pd.DataFrame(data, columns=[
    "customer_id",
    "customer_type",
    "region",
    "credit_limit",
    "risk_profile"
])

customers_df.head()

  customer_id customer_type region  credit_limit risk_profile
0    CUST0001      Hospital  South       4232757          Low
1    CUST0002   Distributor   West       2883642       Medium
2    CUST0003      Hospital  South       1047247       Medium
3    CUST0004      Hospital  South       2797594       Medium
4    CUST0005   Distributor  North       1907053         High

In [6]:
# Insert customers into MySQL
customers_df.to_sql(
    name="customers",
    con=engine,
    if_exists="append",   # Append data into existing table
    index=False
)

print("Customers inserted successfully!")

Customers inserted successfully!

In [7]:
# Fetch customers from SQL
customers_df = pd.read_sql("SELECT * FROM customers", engine)

customers_df.head()

  customer_id customer_type region  credit_limit risk_profile
0    CUST0001      Hospital  South     4232757.0          Low
1    CUST0002   Distributor   West     2883642.0       Medium
2    CUST0003      Hospital  South     1047247.0       Medium
3    CUST0004      Hospital  South     2797594.0       Medium
4    CUST0005   Distributor  North     1907053.0         High

In [8]:
# Generate Invoices:

# Configuration
num_invoices = 10000
credit_term_days = 60

invoice_data = []

for i in range(1, num_invoices + 1):
    
    invoice_id = f"INV{i:05d}"
    
    # Random customer
    customer = customers_df.sample(1).iloc[0]
    customer_id = customer["customer_id"]
    
    # Random invoice date within last 12 months
    start_date = datetime.now() - timedelta(days=365)
    invoice_date = start_date + timedelta(days=random.randint(0, 365))
    
    # Due date = invoice date + 60 days
    due_date = invoice_date + timedelta(days=credit_term_days)
    
    # Invoice amount based on risk
    if customer["risk_profile"] == "Low":
        invoice_amount = random.randint(200000, 800000)
    elif customer["risk_profile"] == "Medium":
        invoice_amount = random.randint(100000, 500000)
    else:
        invoice_amount = random.randint(50000, 300000)
    
    invoice_data.append([
        invoice_id,
        customer_id,
        invoice_date.date(),
        due_date.date(),
        invoice_amount
    ])

invoices_df = pd.DataFrame(invoice_data, columns=[
    "invoice_id",
    "customer_id",
    "invoice_date",
    "due_date",
    "invoice_amount"
])

invoices_df.head()

  invoice_id customer_id invoice_date    due_date  invoice_amount
0   INV00001    CUST0306   2025-04-18  2025-06-17          173985
1   INV00002    CUST0092   2025-09-29  2025-11-28          739959
2   INV00003    CUST0188   2025-09-18  2025-11-17          280953
3   INV00004    CUST0075   2025-06-05  2025-08-04          268914
4   INV00005    CUST0268   2026-02-01  2026-04-02          397955

In [9]:
# Insert into Invoices:

invoices_df.to_sql(
    name="invoices",
    con=engine,
    if_exists="append",
    index=False
)

print("Invoices inserted successfully!")

Invoices inserted successfully!

In [10]:
# Fetch invoices
invoices_df = pd.read_sql("SELECT * FROM invoices", engine)

# Fetch customers
customers_df = pd.read_sql("SELECT customer_id, risk_profile FROM customers", engine)

# Merge to attach risk_profile to each invoice
merged_df = invoices_df.merge(
    customers_df,
    on="customer_id",
    how="left"
)

merged_df.head()

  invoice_id customer_id invoice_date    due_date  invoice_amount risk_profile
0   INV00001    CUST0306   2025-04-18  2025-06-17        173985.0         High
1   INV00002    CUST0092   2025-09-29  2025-11-28        739959.0          Low
2   INV00003    CUST0188   2025-09-18  2025-11-17        280953.0          Low
3   INV00004    CUST0075   2025-06-05  2025-08-04        268914.0         High
4   INV00005    CUST0268   2026-02-01  2026-04-02        397955.0          Low

In [11]:
# Generate Data:

from datetime import timedelta
import random

payment_data = []

for index, row in merged_df.iterrows():
    
    invoice_id = row["invoice_id"]
    due_date = pd.to_datetime(row["due_date"])
    invoice_amount = row["invoice_amount"]
    risk = row["risk_profile"]
    
    # Apply delay logic
    if risk == "Low":
        delay_days = random.randint(-5, 2)
    elif risk == "Medium":
        delay_days = random.randint(5, 15)
    else:  # High
        delay_days = random.randint(20, 45)
    
    payment_date = due_date + timedelta(days=delay_days)
    
    payment_data.append([
        invoice_id,
        payment_date.date(),
        invoice_amount
    ])

payments_df = pd.DataFrame(payment_data, columns=[
    "invoice_id",
    "payment_date",
    "payment_amount"
])

payments_df.head()

  invoice_id payment_date  payment_amount
0   INV00001   2025-07-21        173985.0
1   INV00002   2025-11-23        739959.0
2   INV00003   2025-11-19        280953.0
3   INV00004   2025-08-24        268914.0
4   INV00005   2026-04-02        397955.0

In [12]:
# Insert into MYSQL:

payments_df.to_sql(
    name="payments",
    con=engine,
    if_exists="append",
    index=False
)

print("Payments inserted successfully!")

Payments inserted successfully!