In [7]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, roc_auc_score

In [3]:
engine = create_engine("mysql+pymysql://root:SEEni2003%40@localhost:1611/ar_risk_system")

In [4]:
# Loading of Processed Features:

customer_features = pd.read_sql("SELECT * FROM customer_features", engine)

customer_features.head()

,customer_id,total_invoices,total_amount,avg_delay,max_delay,late_payment_rate,credit_limit,credit_utilization
0,CUST0001,27,13268453.0,-1.555556,2,0.407407,4232757.0,3.134707
1,CUST0002,15,4200530.0,9.933333,13,1.000000,2883642.0,1.456675
2,CUST0003,23,6468998.0,11.478261,15,1.000000,1047247.0,6.177146
3,CUST0004,24,7270672.0,10.541667,15,1.000000,2797594.0,2.598902
4,CUST0005,24,4347214.0,34.416667,44,1.000000,1907053.0,2.279545

In [5]:
# Create Target Variable

customer_features["target_delay"] = customer_features["late_payment_rate"].apply(
    lambda x: 1 if x > 0.3 else 0
)

In [6]:
# Selection of ML Features:

features = [
    "total_invoices",
    "total_amount",
    "avg_delay",
    "max_delay",
    "late_payment_rate",
    "credit_utilization"
]

X = customer_features[features]
y = customer_features["target_delay"]

In [8]:
# Train/Test Split:

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [9]:
# Train Logistic Regression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [10]:
# Evaluate Model

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred))
print("ROC AUC Score:", roc_auc_score(y_test, y_prob))

              precision    recall  f1-score   support

           0       0.75      0.88      0.81        34
           1       0.95      0.88      0.92        86

    accuracy                           0.88       120
   macro avg       0.85      0.88      0.86       120
weighted avg       0.89      0.88      0.89       120

ROC AUC Score: 0.9582763337893296

In [11]:
# Predict Risk Probability for All Customers

customer_features["risk_probability"] = model.predict_proba(X)[:, 1]

In [12]:
# Risk Categorization

def categorize_risk(p):
    if p <= 0.30:
        return "Low"
    elif p <= 0.60:
        return "Medium"
    else:
        return "High"

customer_features["risk_category"] = customer_features["risk_probability"].apply(categorize_risk)

In [13]:
# Credit Recommendation Engine

def adjust_credit(row):
    if row["risk_category"] == "High":
        return row["credit_limit"] * 0.7
    elif row["risk_category"] == "Low":
        return row["credit_limit"] * 1.15
    else:
        return row["credit_limit"]

customer_features["recommended_credit_limit"] = customer_features.apply(adjust_credit, axis=1)

In [14]:
# Calculate Expected Loss

customer_features["expected_loss"] = (
    customer_features["risk_probability"] *
    customer_features["total_amount"]
)

In [15]:
# Save in  a MYSQL :

customer_features.to_sql(
    name="customer_risk_output",
    con=engine,
    if_exists="replace",
    index=False
)

400

In [16]:
customer_features

,customer_id,total_invoices,total_amount,avg_delay,max_delay,late_payment_rate,credit_limit,credit_utilization,target_delay,risk_probability,risk_category,recommended_credit_limit,expected_loss
0,CUST0001,27,13268453.0,-1.555556,2,0.407407,4232757.0,3.134707,1,0.189751,Low,4867670.55,2.517699e+06
1,CUST0002,15,4200530.0,9.933333,13,1.000000,2883642.0,1.456675,1,1.000000,High,2018549.40,4.200530e+06
2,CUST0003,23,6468998.0,11.478261,15,1.000000,1047247.0,6.177146,1,1.000000,High,733072.90,6.468998e+06
3,CUST0004,24,7270672.0,10.541667,15,1.000000,2797594.0,2.598902,1,1.000000,High,1958315.80,7.270672e+06
4,CUST0005,24,4347214.0,34.416667,44,1.000000,1907053.0,2.279545,1,1.000000,High,1334937.10,4.347214e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,CUST0396,22,5906380.0,10.272727,15,1.000000,1182239.0,4.995927,1,1.000000,High,827567.30,5.906380e+06
396,CUST0397,26,11401981.0,-1.692308,2,0.192308,3256515.0,3.501283,0,0.156627,Low,3744992.25,1.785862e+06
397,CUST0398,28,7888927.0,9.392857,15,1.000000,2127387.0,3.708271,1,1.000000,High,1489170.90,7.888927e+06
398,CUST0399,33,9913995.0,9.484848,15,1.000000,1467269.0,6.756767,1,1.000000,High,1027088.30,9.913995e+06
399,CUST0400,29,8607133.0,9.137931,15,1.000000,1432481.0,6.008550,1,1.000000,High,1002736.70,8.607133e+06

In [18]:
# Vaidate the tabels:

# Loading of Processed Features:

customer_risk_output = pd.read_sql("SELECT * FROM customer_risk_output", engine)

In [20]:
customer_risk_output

,customer_id,total_invoices,total_amount,avg_delay,max_delay,late_payment_rate,credit_limit,credit_utilization,target_delay,risk_probability,risk_category,recommended_credit_limit,expected_loss
0,CUST0001,27,13268453.0,-1.555556,2,0.407407,4232757.0,3.134707,1,0.189751,Low,4867670.55,2.517699e+06
1,CUST0002,15,4200530.0,9.933333,13,1.000000,2883642.0,1.456675,1,1.000000,High,2018549.40,4.200530e+06
2,CUST0003,23,6468998.0,11.478261,15,1.000000,1047247.0,6.177146,1,1.000000,High,733072.90,6.468998e+06
3,CUST0004,24,7270672.0,10.541667,15,1.000000,2797594.0,2.598902,1,1.000000,High,1958315.80,7.270672e+06
4,CUST0005,24,4347214.0,34.416667,44,1.000000,1907053.0,2.279545,1,1.000000,High,1334937.10,4.347214e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,CUST0396,22,5906380.0,10.272727,15,1.000000,1182239.0,4.995927,1,1.000000,High,827567.30,5.906380e+06
396,CUST0397,26,11401981.0,-1.692308,2,0.192308,3256515.0,3.501283,0,0.156627,Low,3744992.25,1.785862e+06
397,CUST0398,28,7888927.0,9.392857,15,1.000000,2127387.0,3.708271,1,1.000000,High,1489170.90,7.888927e+06
398,CUST0399,33,9913995.0,9.484848,15,1.000000,1467269.0,6.756767,1,1.000000,High,1027088.30,9.913995e+06
399,CUST0400,29,8607133.0,9.137931,15,1.000000,1432481.0,6.008550,1,1.000000,High,1002736.70,8.607133e+06

In [21]:
final_df = pd.read_sql("SELECT * FROM customer_risk_output", engine)

final_df.head()

,customer_id,total_invoices,total_amount,avg_delay,max_delay,late_payment_rate,credit_limit,credit_utilization,target_delay,risk_probability,risk_category,recommended_credit_limit,expected_loss
0,CUST0001,27,13268453.0,-1.555556,2,0.407407,4232757.0,3.134707,1,0.189751,Low,4867670.55,2.517699e+06
1,CUST0002,15,4200530.0,9.933333,13,1.000000,2883642.0,1.456675,1,1.000000,High,2018549.40,4.200530e+06
2,CUST0003,23,6468998.0,11.478261,15,1.000000,1047247.0,6.177146,1,1.000000,High,733072.90,6.468998e+06
3,CUST0004,24,7270672.0,10.541667,15,1.000000,2797594.0,2.598902,1,1.000000,High,1958315.80,7.270672e+06
4,CUST0005,24,4347214.0,34.416667,44,1.000000,1907053.0,2.279545,1,1.000000,High,1334937.10,4.347214e+06

In [22]:
final_df.to_excel(
    "../data_backup/AI_AR_Risk_Output.xlsx",
    index=False
)

print("Excel file created successfully!")

Excel file created successfully!